[de APP_INFO
  ("name"      "picolisp-supervisor")
  ("version"   "0.22.0")
  ("summary"   "Unicorn-inspired PicoLisp daemon to spawn and manage worker processes")
  ("source"    "https://github.com/aw/picolisp-supervisor")
  ("author"    "Alexander Williams")
  ("license"   "MIT")
  ("copyright" "(c) 2020 Alexander Williams, On-Prem <license@on-premises.com>")
  ("requires"
    ("picolisp-unit"   "v3.0.0"      "https://github.com/aw/picolisp-unit.git") ]
